### ISSUE TITLE
`before` function requires returning true to show

### ISSUE THREAD

**Issue by dsherret** [sydcanem/bootstrap-contextmenu#77]
Code on README.MD doesn't work:

```javascript
$('.context').contextmenu({
  target:'#context-menu', 
  before: function(e,context) {
  }
});
```

You have to explicitly return true to get this to work:

```javascript
$('.context').contextmenu({
  target:'#context-menu', 
  before: function(e,context) {
    return true;
  }
});
```
The documentation says:

> If this function returns false, the context menu will not be displayed.

...but the functionality is more like:

> If this function returns true, the context menu will be displayed.

I have submitted a pull request (#76) with the fix and unit tests for this issue.

**Comment by mjau-mjau** [comment]
+1

**Comment by sydcanem** [comment]
Merged. Thanks.
