### ISSUE TITLE
Get row click ID

### ISSUE THREAD

**Issue by hongoctrien** [sydcanem/bootstrap-contextmenu#79]
Hello.
```html
<table>
     <tr id="row_0">
         <td>a</td>
         <td>b</td>
     </tr>
     <tr id="row_1">
         <td>c</td>
         <td>d</td>
     </tr>
</table>
```
I want get id value this row right click in table.
Please help me. Thank!

**Comment by tosakarin** [comment]
before: function(e,context) {
	    // execute code before context menu if shown
    	  var	 selected_dom=$(e.target).parent().val();
		return true;
	  },

**Comment by hongoctrien** [comment]
:D. hi.
Thank you. 
@tosakarin
