### ISSUE TITLE
Calling closemenu() without argument causes type error

### ISSUE THREAD

**Issue by bzums** [sydcanem/bootstrap-contextmenu#84]
In the function closemenu, at the end e.stopPropagation() is called (https://github.com/sydcanem/bootstrap-contextmenu/blob/master/bootstrap-contextmenu.js#L92). This wil throw an type error when closemenu is called without the event parameter, which can happen, even the plugin itself does that.

```if(e) e.stopPropagation``` fixes that.
Other than that: nice extension :)

**Comment by dzlab** [comment]
I have a similar problem: when the context is visible then I right click somewhere the default context-menu is shown and I get this error `Uncaught TypeError: Cannot read property 'stopPropagation' of undefined`.

**Comment by bzums** [comment]
My fix described in the first post should work for as well.

**Comment by dzlab** [comment]
I think you should create a pull request

**Comment by ohfang** [comment]
same problem

is this extension still maintained?

**Comment by bzums** [comment]
Oh I just saw there was already a push request for this fix...
https://github.com/sydcanem/bootstrap-contextmenu/pull/85

**Comment by KarelCemus** [comment]
+1, please merge the pull request #85

**Comment by ssokolow** [comment]
I'm also experiencing this problem. I'm subscribing to this bug so I know when to reset the `<0.3.3` specifier in my `bower.json`
