### ISSUE TITLE
bug:Uncaught TypeError: Cannot read property 'stopPropagation' of undefined

### ISSUE THREAD

**Issue by chaodongyue** [sydcanem/bootstrap-contextmenu#93]
ContextMenu.closemenu @ bootstrap-contextmenu.js:92
ContextMenu.show @ bootstrap-contextmenu.js:47

**Comment by liyunfang** [comment]
#84   people have been found

**Comment by liyunfang** [comment]
I have a question,There are a number of different menus can appear simultaneously id

**Comment by chaodongyue** [comment]
英语差,能说中文吗

**Comment by liyunfang** [comment]
@chaodongyue  我擦 我以为你是外国人 用的百度翻译
我的意思是说有人已经发现这个问题了  看这个 #84 

我的问题是：如果两个不同的右击菜单(target不同) 会同时出现。理想中应该是只显示一个菜单。

**Comment by liyunfang** [comment]
我做了个扩展 修改了作者的js
https://github.com/liyunfang/yii2-contextmenu

**Comment by chaodongyue** [comment]
@liyunfang 这个确实是问题,貌似作者比较懒

**Comment by Mds92** [comment]
I have the same error !!!!

**Comment by sydcanem** [comment]
Fixed 78d4bfd46889c127e3770e00f477a697aa258229
