### ISSUE TITLE
After open, 2nd right click open a real context menu

### ISSUE THREAD

**Issue by anija** [sydcanem/bootstrap-contextmenu#95]
When i right-click for the first time, everything works fine. But if i right-click again, the browser contextual menu is shown.
I guess it's because the menu it's already open.

**Comment by anija** [comment]
Fixed adding data-toggle="context". The docs are not clear on this point: data-toggle="context" is advised only for implementation by data attributes, but i had to use it with Javascript implementation.

**Comment by nelson6e65** [comment]
:+1:
